### ISSUE TITLE
Add Interactive Attack System

### ISSUE THREAD

**Issue by ghost** [brando56894/dungeon-quest#3]
Right now the battle sequence is non-interactive. I'm thinking of implementing a interactive battle sequence that should also work with team battles. For this to work I would need to define stats (like accuracy, evasiveness, defense, base damage, critical hit chance, etc). It should take me a max of a week to get it up and running.

**Comment by brando56894** [comment]
Go for it! I already have base damages set for the 4 weapons in the buy_weapon, set_current_weapon and find_weapon, all in player.py. You can either use those or make something new. Originally I was trying to create a weapon object with name and damage-dealt properties, but something was getting screwed up when I was calling set_current_weapon so after about a week I abandoned the idea and went with the current objectless implementation.

I think the problem was that I didn't know how to store multiple objects or one object was overwriting the other, because it worked in the find_weapon, buy_weapon and deal_damage functions, but whenever I called set_current_weapon it would execute successfully and tell my current weapon was set to what I wanted, but when I would check my inventory it would be at my previous weapon, usually the dagger since that's the starting weapon.

I think my ultimate plan was to give more experience based on what weapon was used to kill the monster and to add bullets for the guns.
