### ISSUE TITLE
Add more weapons

### ISSUE THREAD

**Issue by brando56894** [brando56894/dungeon-quest#8]
Add more weapons that the player can use, ideas?

**Comment by ghost** [comment]
Dual-wielded weapons that attack twice per turn, but with less damage than their single-wielded version (dual blades, dual pistols, etc)
Staff and magic abilities
bow and/or crossbow
gauntlets (hand to hand combat)
no weapon (hand to hand combat, this could also be default, there would have to be a strength stat since there is no base damage)
helper pet(Computer-controlled: Would only have one special ability and one move that it would use every turn, player only allowed to have a one)

I was thinking we could implement a pokemon style special attack list for each weapon. For example: a sword would have: parry, counter (much like parry, but attacks after blocking), rush (attacks repetitively until enemy dodges, accuracy decreases every attack)

**Comment by ghost** [comment]
Or rather we could create a bunch of skills and spells that would be specific to a certain weapon type and the player can buy these skills at a shop/dojo. We could add sp(skill points) and mp(magic points) that decreases every time the player uses skills and spells. They would need a special type of potion to replenish sp/mp
